FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
ARG VITE_SSO_URL

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SSO_URL=$VITE_SSO_URL

COPY package*.json ./
COPY tailwind.config.js ./
COPY postcss.config.cjs ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
