FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
ARG VITE_SSO_URL

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SSO_URL=$VITE_SSO_URL

COPY package*.json ./

RUN npm install

COPY tailwind.config.js ./
COPY vite.config.js ./
COPY index.html ./
COPY src/ ./src/

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
COPY aurora-fintech.crt /etc/ssl/aurora-fintech.crt
COPY aurora-fintech.key /etc/ssl/aurora-fintech.key
RUN chmod 600 /etc/ssl/aurora-fintech.key && \
    chmod 644 /etc/ssl/aurora-fintech.crt

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
