env: "local"

storage_pass: "postgres://postgres:postgres@postgres:5432/aurora?sslmode=disable"
parsing_service_pass: "postgres://postgres:postgres@postgres:5432/aurora?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44040
  timeout: 10h
redis:
  host: "redis-master:6379"
  password: "1111"
  db: 0
  port: 6379
