env: "local"

storage_pass: "postgres://postgres:Yd%5ETpK%2A%23%29Hfn1%7BV%5BLUWs%2A@postgres:5432/aurora?sslmode=disable"
parsing_service_pass: "postgres://postgres:Yd%5ETpK%2A%23%29Hfn1%7BV%5BLUWs%2A@postgres-parser:5432/parser?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44040
  timeout: 10h
redis:
  host: "redis-master:6379"
  password: "Yd%5ETpK%2A%23%29Hfn1%7BV%5BLUWs%2A"
  db: 0
  port: 6379
