syntax = "proto3";

package recommendation.v1;

option go_package = "recommendation/v1";
import "google/protobuf/timestamp.proto";

service RecommendationService {
  rpc GetUserPriorityChannels(GetUserPriorityChannelsRequest) returns (GetUserPriorityChannelsResponse);
  rpc GetRecommendatedPosts(GetRecommendatedPostsRequest) returns (GetRecommendatedPostsResponse);
  rpc GetAllParsingChannels(GetAllParsingChannelsRequest) returns (GetAllParsingChannelsResponse);
  rpc AddNewParsingChannel(AddNewParsingChannelRequest) returns (AddNewParsingChannelResponse);
  rpc AddNewUserCustomParsingChannel(AddNewUserCustomParsingChannelRequest) returns (AddNewUserCustomParsingChannelResponse);
  rpc DeleteParsingChannel(DeleteParsingChannelRequest) returns (DeleteParsingChannelResponse);
  rpc GetAllParsingChannelsWithCategories(GetAllParsingChannelsWithCategoriesRequest) returns (GetAllParsingChannelsWithCategoriesResponse);
}

message AddNewUserCustomParsingChannelRequest {
  string channel_username = 1;
}

message AddNewUserCustomParsingChannelResponse{

}

message GetAllParsingChannelsWithCategoriesRequest {
  
}

message GetAllParsingChannelsWithCategoriesResponse{
  map<string, ChannelList> channels = 1;
}

message DeleteParsingChannelRequest {
  string channel_username = 1;
}

message DeleteParsingChannelResponse {
}

message AddNewParsingChannelRequest {
  string channel_username = 1;
  string category = 2;
}

message AddNewParsingChannelResponse {
}

message GetAllParsingChannelsRequest {
}

message GetAllParsingChannelsResponse {
  repeated string channels = 1;
}

message GetRecommendatedPostsRequest{
  int64 user_id = 1;
  Cursor cursor = 2;
}

message GetRecommendatedPostsResponse{
  repeated Post posts = 1;
  Cursor next_cursor = 2;
}

message GetUserPriorityChannelsRequest {
  int64 user_id = 1;
}

message GetUserPriorityChannelsResponse{
  repeated string channels = 1;
}

message Cursor{
  int64 score = 1;
  string id = 2;
}

message Post {
  repeated Stock stocks = 1;
  string post_text = 2;
  string post_uri = 3;
  string channel_username = 4;
  string reasoning = 5;
  google.protobuf.Timestamp date = 6;
}

message Stock {
  string stock_name = 1;
  string side = 2;
}

message ChannelList{
  repeated string usernames = 1;
}
