env: "local"

storage_pass: "postgres://postgres:pass@localhost:5432/users?sslmode=disable"
test_postgres_dns: "postgres://postgres:pass@localhost:5432/test_auth?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44044
  timeout: 10h
