env: "local"

storage_pass: "postgres://postgres:Yd%5ETpK%2A%23%29Hfn1%7BV%5BLUWs%2A@postgres:5432/aurora?sslmode=disable"
test_postgres_dns: "postgres://postgres:postgres@postgres:5432/aurora?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44044
  timeout: 10h
