env: "local"

# storage_pass: "postgres://postgres:pass@localhost:5432/users?sslmode=disable"
storage_pass: "postgres://postgres:postgres@aurora-db:5432/aurora?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44044
  timeout: 10h
