env: "local"

storage_pass: ""

auth:
  jwt_secret: "test-secret"
  public_methods:
    - "/api.v1.ApiService/Register"
    - "/api.v1.ApiService/Login"
    - "/api.v1.ApiService/HealthCheck"
    - "/grpc.health.v1.Health/Check"
token_ttl: 1h

redis:
  host: "localhost:6379"
  password: "1111"
  db: 0
  port: 6379

grpc:
  port: 44000
  timeout: 10h

grpc-gateway:
  port: 8081
  timeout: 10h
