FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" \
    -o /app/bin/api-gateway ./cmd/API_Service//main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN adduser -D -g '' appuser

WORKDIR /app

EXPOSE 8081 44000

USER appuser

EXPOSE 8081

CMD ["/app/bin/api-gateway", "--config", "./config/local.yaml"]
