FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./cmd/API_Service

# runtime image
FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN adduser -D -g '' appuser

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/config ./config

USER appuser

EXPOSE 8081

CMD ["./main", "--config", "./config/local.yaml"]
