env: "local"

storage_pass: "postgres://postgres:pass@localhost:5432/users?sslmode=disable"
token_ttl: 1h

grpc:
  port: 44044
  timeout: 10h

redis:
  host: "localhost:6379"
  password: "1111"
  db: 0
  port: 6379
