syntax = "proto3";

import "google/api/annotations.proto";

package api.v1;

import "google/protobuf/timestamp.proto";

option go_package = "api/v1/ApiService";

service ApiService {
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/v1/login"
      body: "*"
    };
  }

  rpc IsAdmin(IsAdminRequest) returns (IsAdminResponse) {
    option (google.api.http) = {
      post: "/v1/is_admin"
      body:"*"
    };
  }
  rpc SetPriorityChannels(SetPriorityChannelsRequest) returns (SetPriorityChannelsResponse) {
    option (google.api.http) = {
      post: "/v1/set_priority_channels"
      body:"*"
    };
  }
  rpc GetRecommendatedPosts(GetRecommendatedPostsRequest) returns (GetRecommendatedPostsResponse) {
    option (google.api.http) = {
      post: "/v1/get_recommendated_posts"
      body:"*"
    };
  }
  rpc GetUserPriorityChannels(GetUserPriorityChannelsRequest) returns (GetUserPriorityChannelsResponse) {
    option (google.api.http) = {
      get: "/v1/get_user_priority_channels"
    };
  }
  rpc DeletePriorityChannels(DeletePriorityChannelRequest) returns (DeletePriorityChannelResponse) {
    option (google.api.http) = {
      post: "/v1/delete_priority_channels"
      body:"*"
    };
  }
  rpc GetAllParsingChannels(GetAllParsingChannelsRequest) returns (GetAllParsingChannelsResponse) {
    option (google.api.http) = {
      post: "/v1/get_all_parsing_channels"
      body:"*"
    };
  }
  rpc AddNewParsingChannel(AddNewParsingChannelRequest) returns (AddNewParsingChannelResponse) {
    option (google.api.http) = {
      post: "/v1/add_new_parsing_channel"
      body:"*"
    };
  }
  rpc DeleteParsingChannel(DeleteParsingChannelRequest) returns (DeleteParsingChannelResponse) {
    option (google.api.http) = {
      post: "/v1/delete_parsing_channel"
      body:"*"
    };
  }
  rpc GetAllParsingChannelsWithCategories(GetAllParsingChannelsWithCategoriesRequest) returns (GetAllParsingChannelsWithCategoriesResponse){
    option (google.api.http) = {
      get: "/v1/get_all_parsing_channels_with_categories"
    };
  }
}

message GetAllParsingChannelsWithCategoriesRequest{
  
}

message GetAllParsingChannelsWithCategoriesResponse{
  map <string, ChannelList> channels = 1;
}

message AddNewParsingChannelRequest {
  string channel_username = 1;
}

message AddNewParsingChannelResponse {
  
}

message DeleteParsingChannelRequest {
  string channel_username = 1;
}

message DeleteParsingChannelResponse {
  
}

message GetAllParsingChannelsRequest {
}

message GetUserPriorityChannelsRequest {
  
}

message GetUserPriorityChannelsResponse {
  repeated string channels = 1;
}

message GetAllParsingChannelsResponse {
  repeated string channels = 1;
}

message DeletePriorityChannelRequest{
  repeated string channels = 1;
}

message DeletePriorityChannelResponse{
}

message GetRecommendatedPostsRequest{
  Cursor cursor = 1;
}

message GetRecommendatedPostsResponse{
  repeated Post posts = 1;
  Cursor next_cursor = 2;
}


message SetPriorityChannelsRequest {
  repeated string priority_channels = 1;
}

message SetPriorityChannelsResponse {
}


message LoginRequest {
  int64 telegram_id = 1;
  string username = 2;
  string first_name = 3;
  string last_name = 4;
  bool is_admin = 5;
  int64 app_id = 6;
}

message LoginResponse {
  string token = 1;
}

message IsAdminRequest {
  int64 telegram_id = 1;
}

message IsAdminResponse {
  bool is_admin = 1;
}

message Post {
  repeated Stock stocks = 1;
  string post_text = 2;
  string post_uri = 3;
  string channel_username = 4;
  string reasoning = 5;
  google.protobuf.Timestamp date = 6;
}

message Stock {
  string stock_name = 1;
  string side = 2;
}
message Cursor{
  int64 score = 1;
  string id = 2;
}

message ChannelList{
  repeated string usernames = 1;
}
